global:
  scrape_interval: 5s

scrape_configs:
  # Existing service
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  # NEW service (risk-decision)
  - job_name: "risk-decision-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]
