server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    cache:
      type: redis
      redis:
        time-to-live: ${CACHE_TTL}
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5-coder:14b

ml:
  model:
    path: ../../ml-risk-model/output/active-model.json

risk:
  policy:
    version: ${RISK_POLICY_VERSION}
    activated_at: ${RISK_POLICY_ACTIVATED_AT}

    maxSingleAmount: ${MAX_SINGLE_AMOUNT}
    maxDailyAmount: ${MAX_DAILY_AMOUNT}
    cardWithdrawalLimit: ${CARD_WITHDRAWAL_LIMIT}

    blockedCountries:
      - PK
      - BD
      - AF

    maxFutureDrift: PT2M
    maxPastDrift: PT12H ##PT5M

    declineThreshold: ${DECLINE_THRESHOLD}
    reviewThreshold: ${REVIEW_THRESHOLD}

    softRules:
      highAmount: ${SOFT_HIGH_AMOUNT}
      mediumAmount: ${SOFT_MEDIUM_AMOUNT}

      velocityHigh: ${VELOCITY_HIGH}
      velocityMedium: ${VELOCITY_MEDIUM}

      cardHighAmount: ${CARD_HIGH_AMOUNT}

      deltas:
        low: ${DELTA_LOW}
        medium: ${DELTA_MEDIUM}
        high: ${DELTA_HIGH}
        critical: ${DELTA_CRITICAL}

resilience4j:
  retry:
    instances:
      keycloakRetry:
        max-attempts: 3
        wait-duration: 500
        exponential-backoff-multiplier: 2

logging:

  pattern:
    console: ${LOG_PATTERN}

  level:

    root: INFO

    # BUSINESS
    com.gringotts: INFO

    # SPRING
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

    # FEIGN
    org.springframework.cloud.openfeign: INFO

    # DATABASE
    com.zaxxer.hikari: WARN

management:
  endpoints:
    web:
      exposure:
        include: ${USER_ACTUATOR_ENDPOINTS:health,metrics}
  metrics:
    tags:
      application: risk-decision-service
  endpoint:
    health:
      show-details: always