server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}

    show-sql: ${HIBERNATE_SHOW_SQL}

    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL}
        highlight_sql: ${HIBERNATE_HIGHLIGHT_SQL}
        dialect: ${HIBERNATE_DIALECT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  security:
    oauth2:

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  jackson:
    serialization:
      write-dates-as-timestamps: false

# =============================================================
# SERVICE-TO-SERVICE KEYCLOAK CONFIG
# =============================================================
keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

outbox:
  batch-size: ${OUTBOX_BATCH_SIZE}
  max-retry: ${OUTBOX_MAX_RETRY}
  scheduler-delay-ms: ${OUTBOX_SCHEDULER_DELAY_MS}

risk:
  service:
    url: ${RISK_SERVICE_URL}

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT}
        readTimeout: ${FEIGN_READ_TIMEOUT}
        loggerLevel: ${FEIGN_LOGGER_LEVEL}

  okhttp:
    enabled: true

resilience4j:
  retry:
    instances:

      keycloakToken:
        maxAttempts: ${KEYCLOAK_RETRY_MAX_ATTEMPTS}
        waitDuration: ${KEYCLOAK_RETRY_WAIT_DURATION}

      riskService:
        maxAttempts: ${RISK_RETRY_MAX_ATTEMPTS}
        waitDuration: ${RISK_RETRY_WAIT_DURATION}
        exponential-backoff-multiplier: ${RISK_RETRY_EXPONENTIAL_BACKOFF}

        retryExceptions:
          - java.io.IOException
          - feign.RetryableException
          - java.net.SocketTimeoutException

  circuitbreaker:
    instances:

      riskService:
        slidingWindowSize: ${RISK_CB_SLIDING_WINDOW_SIZE}
        minimumNumberOfCalls: ${RISK_CB_MINIMUM_CALLS}
        failureRateThreshold: ${RISK_CB_FAILURE_THRESHOLD}
        waitDurationInOpenState: ${RISK_CB_WAIT_DURATION_OPEN_STATE}
        permittedNumberOfCallsInHalfOpenState: ${RISK_CB_HALF_OPEN_CALLS}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"